### ISSUE TITLE
Support RDS IAM authentication

### ISSUE THREAD

**Issue by dudicoco** [crossplane-contrib/provider-sql#106]
Hi,

It seems that currently RDS IAM authentication for mysql/postgresql users is not possible with the provider.

Here are the official docs: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.DBAccounts.html

For mysql it is necessary to set `AWSAuthenticationPlugin` when creating the user.

For postgresql the user must be granted the `rds_iam` role.

This possible with the Terraform providers:
https://registry.terraform.io/providers/bangau1/mysql/latest/docs/resources/user
https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_grant_role

**Comment by AdamRussak** [comment]
Hi,
I want to add the `AWSAuthenticationPlugin ` to MySQL.

Would someone be able to point me to / guide me? 
I'm good with GO but didn't contribute here yet :)

**Comment by tenitski** [comment]
This works for RDS IAM auth:

```yaml
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  defaultDatabase: example
  sslMode: require
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: default
      name: example-secret
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: examplerole
  annotations:
    crossplane.io/external-name: "you_can_also_have_underscores_in_role_name"
spec:
  forProvider:
    privileges:
      login: true
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: mainrole
spec:
  forProvider:
    memberOf: exampleuser
    roleRef:
      name: examplerole
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: iamrole
spec:
  forProvider:
    memberOf: rds_iam
    roleRef:
      name: examplerole
```
