### ISSUE TITLE
Installation of this provider

### ISSUE THREAD

**Issue by msonnleitner** [crossplane-contrib/provider-sql#14]
I was trying to install this provider with something analogous to https://github.com/crossplane-contrib/provider-ibm-cloud

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-sql
spec:
  package: "crossplane/provider-sql:alpha"
```

After reading that comment, does this mean the provider is not yet published or am I doing something wrong (just trying out Crossplane without much experience)?

Looks like the "Login to Docker" and "Publish Artifacts" steps are being skipped: https://github.com/crossplane-contrib/provider-sql/runs/1417312119?check_suite_focus=true

_Originally posted by @srueg in https://github.com/crossplane-contrib/provider-sql/issues/5#issuecomment-729567219_

**Comment by srueg** [comment]
You're on the right track. You just have to use the `master` tag:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-sql
spec:
  package: "crossplane/provider-sql:master"
```

There are no released versions of this provider yet. Once it implements a little more functionality we'll create a release you can use to install it.
