### ISSUE TITLE
Failure to GET provider v0.9.0

### ISSUE THREAD

**Issue by seanlucey** [crossplane-contrib/provider-sql#169]
### What happened?
Unable to retrieve provider-sql package 0.9.0 when upgrading Provider from v0.7.0. Getting the following when Provider is unable to spin up:
`HEAD https://index.docker.io/v2/crossplane/provider-sql/manifests/v0.9.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details): GET https://index.docker.io/v2/crossplane/provider-sql/manifests/v0.9.0: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v0.9.0`

### How can we reproduce it?
Upgrade provider using Provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-sql-provider
spec:
  package: crossplane/provider-sql:v0.9.0
```

### What environment did it happen in?
Crossplane version: 1.12.2
