### ISSUE TITLE
Implement PostgreSQL Role management

### ISSUE THREAD

**Issue by benagricola** [crossplane-contrib/provider-sql#17]
### What problem are you facing?
Lack of Postgres User management.

### How could Crossplane help solve your problem?
Note: `CREATE USER` in recent Postgres versions is an alias for [`CREATE ROLE WITH LOGIN`](https://www.postgresql.org/docs/current/sql-createrole.html), so the following is written on the assumption that we're using the current Postgres term rather than looking for parity with the MySQL resource.

 - Implement a new Crossplane managed resource `Role` in `postgresql.sql.crossplane.io`.
 - Implement a new reconciler for `Role`.
 - Good initial support: all 'booleans' except `INHERIT` outlined in `CREATE ROLE` doco above, with at least plaintext password support.
 - `INHERIT` boolean only necessary with nested roles.

# Sketch

```yaml
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: example-role
spec:
  forProvider:

    # Either: Separate fields (Values are suggested defaults)
    superuser: false
    createDb: false
    createRole: false
    inherit: false
    login: true
    replication: false
    bypassRLS: false

    # OR: Implemented like the MySQL Grant type (I prefer this one)
    privileges:
      - NOSUPERUSER
      - NOCREATEDB
      - NOCREATEROLE
      - NOINHERIT
      - LOGIN
      - NOREPLICATION
      - NOBYPASSRLS

    # Subsequent functionality
    inRoleRefs:
      - name: other-role-1
        namespace: default
      - name: other-role-2
        namespace: default

    passwordSecretRef:
      name: example-pw
      namespace: default
      key: password

  writeConnectionSecretToRef:
    name: example-connection-secret
    namespace: default
```

Happy to look at a PR for this once API design is agreed upon.

e: `GRANT` also necessary of course, but would prefer to approach as 2 separate issues :)
