### ISSUE TITLE
Cannot grant load from S3 to user

### ISSUE THREAD

**Issue by stevewhitaker-oc** [crossplane-contrib/provider-sql#176]
### What happened?
I am using AWS' RDS & to be able to load data from S3 you need to add the following grant
`GRANT LOAD FROM S3`

But because there is a `3` in the grant it fails the enforced pattern `pattern: ^[A-Z_ ]+$`

### How can we reproduce it?
Try to grant load from s3 to a user

```
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: test-user-s3
spec:
  forProvider:
    privileges:
      - "GRANT LOAD FROM S3"
    userRef:
      name: test-user
  providerConfigRef:
    name: provider-sql
```

### What environment did it happen in?
Crossplane version:  v1.15.0

* Cloud provider: AWS EKS
* Kubernetes version: 1.28
