### ISSUE TITLE
MySQL Grant privileges arbitrary SQL injection

### ISSUE THREAD

**Issue by benagricola** [crossplane-contrib/provider-sql#18]
### What happened?
Looking through the MySQL `Grant` reconciler code, I noticed that `Spec.ForProvider.Privileges` is [passed directly](https://github.com/crossplane-contrib/provider-sql/blob/b4765ac1ca4b987b84c573c26f523e055b4729c9/pkg/controller/mysql/grant/reconciler.go#L257) into `createGrantQuery` and `fmt.Sprintf`'d into the SQL query. 

### How can we reproduce it?
Since the `Privileges` field is not sanity checked on input, it can contain any string the user chooses, example (untested):

```yaml
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: inject-grant
spec:
  forProvider:
    privileges:
      - "ALL ON *.* TO '*'@'*'; RESTART; -- ",
```

Which would execute the following SQL queries, assuming relevant access: 

```
GRANT ALL ON *.* TO '*'@'*'; RESTART; --  (comment) ...
```

I don't believe `database/sql` does anything further to protect from this. 

### What environment did it happen in?
Crossplane version: master
Provider version: master

### Fix
Privilege types cannot be quoted in the query, so should not be passed in directly from unsanitised user input.

I can think of a couple of options:
  * Sanitise the privileges list against a list of known privileges using `// +kubebuilder:validation:Enum=...` (This would ned to support multi-word enum values like `LOCK TABLES`...)
  * Switch input style somehow (boolean for each privilege?) so that privilege list is generated internally from user input
