### ISSUE TITLE
provider-sql can not connect to Azure PostgeSQL server (cannot select database)

### ISSUE THREAD

**Issue by haraldatbmw** [crossplane-contrib/provider-sql#23]
### What happened?
I'm trying to use the provider-azure in combination with provider-sql.
My Azure postgresql db server was created but the creation of a new database fails with the error below.

It seems that Azure refuse connections where dsn does not contain the name of the default-database.
See https://github.com/crossplane-contrib/provider-sql/blob/878ec89a66aa1a50bec40f58bf74f360226a9a09/pkg/clients/postgresql/postgresql.go#L25

```
DEBUG    provider-sql    
Cannot observe external resource    {
	"controller": "managed/database.postgresql.sql.crossplane.io", 
	"request": "/example", 
	"uid": "c9851c7c-5162-487b-ae49-ba842b1e32be", 
	"version": "53079694", 
	"external-name": "example", 
	"error": "cannot select database: pq: Invalid connection parameters specified. Check connection parameters, and try again.", 
	"errorVerbose": "pq: Invalid connection parameters specified. Check connection parameters, and try again.
	cannot select database
	github.com/crossplane-contrib/provider-sql/pkg/controller/postgresql/database.(*external).Observe
		/home/runner/work/provider-sql/provider-sql/pkg/controller/postgresql/database/reconciler.go:163
	github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.12.0/pkg/reconciler/managed/reconciler.go:588
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
	k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
	k8s.io/apimachinery/pkg/util/wait.Until
		/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
	runtime.goexit
		/opt/hostedtoolcache/go/1.14.14/x64/src/runtime/asm_amd64.s:1373", 
	"requeue-after": "2021-02-17T12:59:13.393Z"
}
```

### How can we reproduce it?
Apply these resources:

```
---
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: crossplane-resourcegroup
spec:
  location: westeurope
---
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: crossplane-postgresql
spec:
  forProvider:
    createMode: Default
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: crossplane-resourcegroup
    location: westeurope
    sslEnforcement: Disabled
    version: "11"
    sku:
      tier: GeneralPurpose
      capacity: 2
      family: Gen5  
    storageProfile:
      backupRetentionDays: 35
      geoRedundantBackup: Disabled
      storageAutogrow: Disabled
      storageMB: 5120
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: crossplane-postgresql-conn
  providerConfigRef:
    name: default
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: sql-provider-config
spec:
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: crossplane-postgresql-conn
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example
spec:
  forProvider: {}
  providerConfigRef:
    name: sql-provider-config
```

### What environment did it happen in?
Crossplane version:  1.0.0

**Comment by benagricola** [comment]
Looks like this also causes issues when using `masterUsername` with `RDSInstance` from `provider-aws`. `pq` defaults to connecting to a database with the same name as the user you connect as, so if you change the default username of the database then `provider-sql` will no longer be able to connect, throwing an error: `pq: database "<masterUsername>" does not exist`.

ISTM that allowing this setting to be overridden in `ProviderConfig` is a safe bet, and defaulting it to `postgres` otherwise, to make sure it always exists in the DSN is probably a smart idea.

**Comment by haraldatbmw** [comment]
I was able to workaround this issue by setting the database using an environment variable in the ControllerConfig.
https://github.com/lib/pq/blob/aecc8114c9f8b75fd4118600cbf1f8394090e69f/conn.go#L1973

The manifest for the provider-sql looks like this:

```yaml
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: sql-config
spec:
  env:
  - name: PGDATABASE
    value: postgres
  - name: PGSSLMODE
    value: disable
  args:
  - "--debug"
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-sql
spec:
  controllerConfigRef:
    name: sql-config
```
