### ISSUE TITLE
(postgresql) Grant privileges on database - external resource existence never confirmed

### ISSUE THREAD

**Issue by aawoznia26** [crossplane-contrib/provider-sql#240]
### What happened?
When granting database privileges to a role that already has some existing privileges for the same database and grant option, the managed resource never reaches a ready state. Most probably issue is in [grant validation query](https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/controller/postgresql/grant/reconciler.go#L218) expecting exactly the same array of privileges to be granted as specified in manages resource. For example, the actual privileges value assigned to the role is `{CONNECT,CREATE,TEMPORARY}`, while the validation query only expects `{CONNECT}`

### How can we reproduce it?
Create database and role
```
CREATE ROLE "my-service_user" PASSWORD 'mKMTrwhl79' INHERIT NOCREATEDB NOCREATEROLE LOGIN;
GRANT "my-service_user" TO "postgres";
ALTER ROLE "my-service_user" CONNECTION LIMIT -1;
CREATE DATABASE "my-service" OWNER "my-service_user" ALLOW_CONNECTIONS true CONNECTION LIMIT -1;
```
Then add grant
```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant
spec:
  deletionPolicy: Delete
  forProvider:
    database: my-service
    privileges:
      - CONNECT
    revokePublicOnDb: true
    role: my-service_user
  managementPolicies:
    - '*'
  providerConfigRef:
    name: postgresql-config
```
Check status
`kubectl get grants.postgresql.sql.crossplane.io example-grant -o jsonpath='{.status.conditions}' | jq '.'`

Ready is false, while expected is true
```
[
  {
    "lastTransitionTime": "2025-05-30T17:30:29Z",
    "reason": "Creating",
    "status": "False",
    "type": "Ready"
  },
  {
    "lastTransitionTime": "2025-05-30T17:30:29Z",
    "reason": "ReconcileSuccess",
    "status": "True",
    "type": "Synced"
  }
]
```

provider-sql logs
```
2025-05-30T17:34:35Z	DEBUG	provider-sql	Waiting for external resource existence to be confirmed	{"controller": "managed/grant.postgresql.sql.crossplane.io", "request": {"name":"example-grant"}, "uid": "3df4922e-a5ca-4d07-bb77-3bad096dfacc", "version": "568185", "external-name": "example-grant"}
2025-05-30T17:34:35Z	DEBUG	events	Waiting for external resource existence to be confirmed	{"type": "Normal", "object": {"kind":"Grant","name":"example-grant","uid":"3df4922e-a5ca-4d07-bb77-3bad096dfacc","apiVersion":"postgresql.sql.crossplane.io/v1alpha1","resourceVersion":"568185"}, "reason": "PendingExternalResource"}
```

### What environment did it happen in?
Crossplane version: 
- Client Version: v1.17.0
- Server Version: v1.17.0

Kubernetes version: 
- Client Version: v1.29.6
- Server Version: v1.29.6+k3s2

provider-sql version: 0.11.0

**Comment by dcader-thulium** [comment]
We experience the same issue.

provider-sql version: tested on `v0.14.0` and `v0.15.0`
crossplane version: `2.2.1`

**Comment by niralmehtasb1** [comment]
We are experiencing the same issue with function grants on **v0.16.0-beta.0**.
  
  Use case: Granting EXECUTE on a specific function in a PostgreSQL extension (aws_s3) to a role via a Crossplane composition.

  Grant resource spec:
```
  apiVersion: postgresql.sql.crossplane.io/v1alpha1
  kind: Grant
  spec:
    forProvider:
      privileges:
        - EXECUTE
      schema: aws_s3
      routines:
        - name: table_import_from_s3
          args:
            - text
            - text
            - text
            - text
            - text
            - text
            - text
            - text
            - text
      role: <mydbrole>
      database: <mytestdb>
```

  Observed behaviour:
  - Synced=True, ReconcileSuccess — the SQL is executed successfully.
  - Provider immediately enters Waiting for external resource existence to be confirmed loop.
  - Ready=False permanently.

  Verified in DB:
  SELECT grantee, privilege_type, routine_name, specific_schema
  FROM information_schema.routine_privileges
  WHERE routine_name = 'table_import_from_s3'
    AND grantee = "mydbrole";
  -- returns 1 row confirming the grant exists

  The grant is applied in PostgreSQL but the observe reconciliation cannot confirm it, consistent with the root cause described in this issue.

  Additional blocker: The CRD validates routines[].args items against ^[a-zA-Z_][a-zA-Z0-9_$]*$ which rejects dots, making it impossible to express PostgreSQL composite types (e.g. aws_commons._s3_uri_1) as function arguments. This prevents granting on function overloads that use
  composite type parameters entirely.

**Environment:**
  - provider-sql version: `v0.16.0-beta.0`
  - Crossplane version: `v2.1.4`
