### ISSUE TITLE
PostgreSQL Grant databaseSelector, roleSelector are not finding resource

### ISSUE THREAD

**Issue by haraldatbmw** [crossplane-contrib/provider-sql#29]
### What happened?
I want to compose a azure postgresql-server and a **database**, a **role** and a **grant** inside a crossplane composite.
The grant needs references to the database and the role.
Therefor I tried to use `roleSelector` and `databaseSelector` without success.

The events on the grant resource looks like this:

```
Events:                                                                                                                                                                                                                      
   Type     Reason                           Age                  From                                        Message                                                                                                         
   ----     ------                           ----                 ----                                        -------                                                                                                         
   Warning  CannotResolveResourceReferences  84s (x304 over 31m)  managed/grant.postgresql.sql.crossplane.io  cannot resolve references: spec.forProvider.database: cannot list resources that match selector: expected point 
 er, but got invalid kind
```

### How can we reproduce it?
```yaml
  ...

  # database on the postgresql-server
  - name: postgresqldatabase
    base:
      apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      metadata:
        labels:
          example: label
      spec:
        forProvider: {}
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "spec.parameters.dbName"
      toFieldPath: "metadata.annotations[crossplane.io/external-name]"
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.providerConfigRef.name"
      transforms:
      - type: string
        string:
          fmt: "sql-provider-config-%s"
  # connection role
  - name: postgresqlrole
    base:
      apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Role
      spec:
        forProvider:
          connectionLimit: 10
          privileges:
            login: true
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "spec.parameters.dbName"
      toFieldPath: "metadata.annotations[crossplane.io/external-name]"
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.providerConfigRef.name"
      transforms:
      - type: string
        string:
          fmt: "sql-provider-config-%s"
    connectionDetails:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - name: hostname
      fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
  # grants for connection role
  - name: postgresqlgrant
    base:
      apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Grant
      spec:
        forProvider:
          privileges:
            - CONNECT
            - TEMPORARY
          roleSelector:
            matchControllerRef: true
          databaseSelector:
            matchControllerRef: true
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.providerConfigRef.name"
      transforms:
      - type: string
        string:
          fmt: "sql-provider-config-%s"
```

### What environment did it happen in?
Crossplane version: 1.1.0
