### ISSUE TITLE
Provision MySQL Grants

### ISSUE THREAD

**Issue by srueg** [crossplane-contrib/provider-sql#3]
Implement support for provisioning MySQL [grants](https://mariadb.com/kb/en/grant/) for users. In addition to provisioning databases and users on SQL servers grants should also be supported. We'll start with the implementation for MySQL. Support for PostgreSQL can follow later.

## Implementation Details
* Create a new manged resource `Grant` in `mysql.sql.crossplane.io/v1alpha1` with the following fields:
  * `.spec.forProvider.rawGrants` string array of raw `GRANT` statements
  * `spec.forProvider.grants` array with typed grants:
    * `.userRef` reference to a `User` resource (see #2) to which to apply the grant (e.g. `GRANT ... TO username`)
    * `.databaseRef` reference to a `Database` resource to which to apply the grant (e.g. `GRANT ... ON db_name.* ...`)
    * `.privileges` array of [privileges](https://mariadb.com/kb/en/grant/#database-privileges) to grant (e.g. `GRANT ... ALL ...`)
* Implement a new `grant` reconciler in the `pkg/controller/mysql/grant` package
* Provision a grant based on the CRD

## To be Discussed
How much logic should be provided to create grants?
I think the approach with both a `rawGrant` to define arbitrary statements and the typed `grants` fields would allow a simple solution for the most basic use cases and a more advanced way for fine granular permissions.

**Comment by negz** [comment]
@srueg What do you think about something like this?

```yaml
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  # ...
spec:
  # A plain string - this user doesn't need to be known to Crossplane.
  user: foo
  # A cross resource reference to a MySQL "User" managed resource.
  # Used to set 'user' above.
  # userRef:
  #   name: foouser
  # A plain string - this databse doesn't need to be known to Crossplane.
  database: foo
  # A cross resource reference to a MySQL "Database" managed resource.
  # Used to set 'database' above.
  # databaseRef:
  #   name: foodb
  privileges: ['some', 'privs']
```

The key points here are:

* A `Grant` represents at most one grant, not many.
* We allow the author to grant users access to databases even if the user and/or database are not managed by Crossplane (which I presume was the goal of the `rawGrants` approach).
