### ISSUE TITLE
Deploy provider-sql from source on k8s

### ISSUE THREAD

**Issue by cwesdorp** [crossplane-contrib/provider-sql#45]
### What problem are you facing?
This is more like a question on developer convenience as a feature request. I can build the tool locally and deploy but need to jump some hoops. Hope to learn some things here.

When building the package and images the result is a docker image `build-1f5fc5f1/provider-sql-amd64:latest` in my local registry. I can deploy this to a k8s clusters by deploying the Provider resource like this where `package` points to this local registry.

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-sql
  annotations:
    descriptionShort: |
      The SQL Crossplane provider enables management of SQL servers.
spec:
  package: 10.211.55.2:5000/build-1f5fc5f1/provider-sql-amd64:latest
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
```

However, the `provider-sql-amd64:latest` is created based on the content from the `package` folder and includes `crossplane.yaml` which has as controller reference

```
spec:
  controller:
    image: crossplane/provider-sql-controller:VERSION
```

When deploying the Provider resource this leads to an image pull error for the controller.

### How could Crossplane help solve your problem?
Is there an option other then changing `package/crossplane.yaml` manually to get the provider-sql package image generated with the correct controller image reference, namely the `build-1f5fc5f1/provider-sql-controller-amd64:latest` that is available locally, or another way to alias `crossplane/provider-sql-controller:VERSION` to the local version?
