### ISSUE TITLE
Example of db-conn secret?

### ISSUE THREAD

**Issue by kferrone** [crossplane-contrib/provider-sql#52]
### What problem are you facing?

There is no example of how to create the `db-conn` secret for the ProviderConfig?
What is supposed to be in this secret?

### How could Crossplane help solve your problem?

Give an example of what the secrets for Postgresql and Mysql

**Comment by kferrone** [comment]
I made a secret like this with the following keys:
```json
{
  "user": "postgres",
  "password": "password",
  "endpoint": "postgresql.svc",
  "port": "5432"
}
```
I found some hints in the code.
Unfortunately I can't get a DB to actually provision on Postgresql.
I put root credentials in the secret even, so permission shouldn't be an issue. 

Here is the error I get on the DB resource in the status:
```
observe failed: cannot select database: pq: Could not detect default
        username. Please provide one explicitly
```
Here is my ProviderConfig, does it look right?
```yaml
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  defaultDatabase: postgres
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane
      name: postgresql
```
