### ISSUE TITLE
Support underscore in Database name

### ISSUE THREAD

**Issue by uqix** [crossplane-contrib/provider-sql#59]
### What problem are you facing?

Our db names contain underscore which is not allowed in k8s `metadata.name` 

### How could Crossplane help solve your problem?

Maybe `provider-sql` could provide an option for we specifying a name other than using `metadata.name` as the db name?

**Comment by luis-alen** [comment]
This would be nice indeed and it's kinda related to what I said here https://github.com/crossplane-contrib/provider-sql/issues/58#issuecomment-1008059074

**Comment by petteja** [comment]
What about using the `crossplane.io/external-name` annotation? The following will create a database with the name `db_with_underscore`

```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    crossplane.io/external-name: db_with_underscore
  name: example
spec:
  forProvider: {}
```
