### ISSUE TITLE
How to diagnose problems if resources stuck in not ready state?

### ISSUE THREAD

**Issue by uqix** [crossplane-contrib/provider-sql#60]
### What problem are you facing?

Pods in `crossplane-system` namespace do not log any error, so we have no idea what's wrong.

### How could Crossplane help solve your problem?

Maybe add some error logs?

**Comment by MattMencel** [comment]
@uqix I just discovered this myself. Debug logging can be enable by adding a `ControllerConfig` object.

``` yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
```
