### ISSUE TITLE
role.postgresql: Support for configuration parameters

### ISSUE THREAD

**Issue by petteja** [crossplane-contrib/provider-sql#68]
### What problem are you facing?
Need to be able to set role configuration parameters. This is useful for instance together with the pgaudit extension where you can do `alter role myrole set pgaudit.log='All'` to audit the actions of myrole.

https://www.postgresql.org/docs/current/sql-alterrole.html

### How could Crossplane help solve your problem?
I suggest introducing configurationParameters where name value pairs can be defined and applied to the role.
```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: parent-role
spec:
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
    configurationParameters:
      - name: 'pgaudit.log'
        value: 'All'
      - name: 'search_path'
        value: '"$user",public'
```
