### ISSUE TITLE
postgresql - add support for "ALL" Privileges 

### ISSUE THREAD

**Issue by tilegg** [crossplane-contrib/provider-sql#92]
### What problem are you facing?
Grants for ALL privileges are not becoming ready

Example:
```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-role2-on-example-db
spec:
  forProvider:
    databaseRef:
      name: example-db
    roleRef:
      name: example-role
    privileges:
      - ALL
  providerConfigRef:
    name: postgres-example
```

### How could Crossplane help solve your problem?
The issue is due to postgresql basically interpolating ALL as CREATE, TEMPORARY, CONNECT (for databases). https://www.postgresql.org/docs/12/ddl-priv.html#PRIVILEGE-ABBREVS-TABLE

provider-sql expects the permissions to be ALL but the query returns false as they are "CREATE, TEMPORARY, CONNECT", therefore provider-sql tries to reconcile but never succeeds.

I've implemented a small PoC for databases (will link PR) that basically just mimics the interpolation postgres does for the observe function. If this approach makes sense to you it needs to be added to the other relevant resources. Also I was not able to figure out if and how to create a UnitTest for this.
