### ISSUE TITLE
role.postgresql - Taking ownership of existing role gives panics

### ISSUE THREAD

**Issue by petteja** [crossplane-contrib/provider-sql#99]
### What happened?
https://github.com/crossplane-contrib/provider-sql/pull/69 introduced a bug when taking ownership of existing role, causing panic.

### How can we reproduce it?
Create role with deletionPolicy: Orphan
```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: role1
  annotations:
    crossplane.io/external-name: role1
spec:
  deletionPolicy: Orphan
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
  providerConfigRef:
    name: rds
  writeConnectionSecretToRef:
    name: examsfa
    namespace: default
```
Delete it and then apply again.
```
goroutine 751 [running]:                                                                                                                                 
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009e6ba0})                                                                               
        /home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:55 +0xd8                   
panic({0x1444840, 0x23e8ec0})                                                                                                                            
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1038 +0x215                                                                             
github.com/crossplane-contrib/provider-sql/pkg/controller/postgresql/role.(*external).Update(0xc000dc2b20, {0x17e9320, 0xc000706420}, {0x1832e48, 0xc00108
0000})                                                                                                                                                   
        /home/runner/work/provider-sql/provider-sql/pkg/controller/postgresql/role/reconciler.go:383 +0x67b                                              
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0000a9ea0, {0xc000776680, 0x1442ec0}, {{{0x0, 0x14dbf40}, {0xc0
0087a900, 0xc000af0080}}}) 
```                                                                                                                              

### What environment did it happen in?
provider-sql version: 0.5.0
